### PR TITLE
igor-lig-1153-add-instructions-on-how-to-run-docker-as

### PR DESCRIPTION
**Pull request by IgorSusmelj**
## Changes

- Add instructions on how to use docker as non-root user

### CODE REVIEW

**Review by MalteEbner — COMMENTED** [review]
The code looks good to me. Could you add a screenshot or pdf of how it looks like?

**Comment by IgorSusmelj** [comment]
> The code looks good to me. Could you add a screenshot or pdf of how it looks like?

Could you elaborate on what you mean with this?

**Comment by MalteEbner** [comment]
> > The code looks good to me. Could you add a screenshot or pdf of how it looks like?
> 
> Could you elaborate on what you mean with this?

If we change the docs, we usually add a pdf of the changed page, or a screenshot of it to the PR text. Example: https://github.com/lightly-ai/lightly/pull/803

**Comment by IgorSusmelj** [comment]
[Setup — lightly 1.2.16 documentation.pdf](https://github.com/lightly-ai/lightly/files/8753135/Setup.lightly.1.2.16.documentation.pdf)

This part only highlights the changes: 
image

**Review by MalteEbner — APPROVED** [review]
Looks good to me.

**Pull request merged**
