### PR TITLE
Jeremy lig 4470 proxy

### PR DESCRIPTION
**Pull request by japrescott**
closes lig-4470
closes https://github.com/lightly-ai/lightly/issues/1492

**Changes**
- if `ALL_PROXY`, `HTTPS_PROXY` or `HTTP_PROXY` environment vars are set, pass that information to swagger which triggers the usage `urllib3.ProxyManager`. According to [Olivier Benz](https://github.com/lightly-ai/lightly/issues/1492) this should resolve the issue of using lightly behind a corporate mitm proxy.

**Tests**
- no manual tests have been done. Needs to be tested once it landed in the worker and tested behind a proxy in the future. However these changes should not have any impact on existing users.

### CODE REVIEW

**Review by MalteEbner — APPROVED** [review]

**Comment by nasserdr** [comment]
Hello,

I am still having the issue of connecting to lightly server despite configuring the env variables for the API:

For instance, trying to download the embeddings as per the code below:

```
os.environ['LIGHTLY_CA_CERTS'] = '/etc/ssl/certs/ca-certificates.crt'
from lightly.api import ApiWorkflowClient
client = ApiWorkflowClient(token=lightly_key, dataset_id=dataset_id)
client.download_embeddings_csv(output_path="embedding_lightly.csv")
client.download_embeddings_csv_by_id(
    embedding_id="639311ded9bf8c106b6d8881",
    output_path="embedding.csv",
)
```

give me this error:
```
2025-07-01 15:01:06,592 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x74c6ae944a90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /v1/datasets/<DATASET_ID>/embeddings?token=<MYTOKEN>
2025-07-01 15:01:06,592 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x74c6ae944a90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /v1/datasets/<DATASET_ID>/embeddings?token=<MYTOKEN>
2025-07-01 15:01:06,592 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x74c6ae944a90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /v1/datasets/<DATASET_ID>/embeddings?token=<MYTOKEN>
```

I shadowed the token and dataset id with <MYTOEKN> and <DATASET_ID> respectively for security reasons

**Comment by MalteEbner** [comment]
> Hello,
> 
> I am still having the issue of connecting to lightly server despite configuring the env variables for the API:

Hey @nasserdr,

sorry that you encounter this error. I assume that it fails because you set `os.environ['LIGHTLY_CA_CERTS'] = '/etc/ssl/certs/ca-certificates.crt'` after the lightly ApiWorflowClient and thus urllib have been imported. Thus best try setting the environment variable before all other imports or even better outside the script.

If this does not help, can you provide the following debugging information?
- The package version via `pip show lightly`
- What happens if you set `os.environ['LIGHTLY_CA_CERTS'] ` i) outside of the script before it and ii) not at all

**Comment by nasserdr** [comment]
Thank you @MalteEbner  for your feedback. In my comment above,  the env variable is - indeed - declared well before importing the lightly api. 

this is what pip lightly show outputs:

`pip show lightly
Name: lightly
Version: 1.4.8
Summary: A deep learning package for self-supervised learning
Home-page: 
Author: Philipp Wirth & Igor Susmelj
Author-email: philipp@lightly.ai
License: MIT
Location: /home/f80859433@agsad.admin.ch/miniconda3/envs/rumexenv/lib/python3.10/site-packages
Requires: aenum, certifi, hydra-core, lightly-utils, numpy, pydantic, python-dateutil, pytorch-lightning, requests, setuptools, six, torch, torchvision, tqdm, urllib3, urllib3
Required-by:`

Finally, if I defined the env variable in another script, the other script is unfortunately unaware of it.

**Comment by benz0li** [comment]
> Finally, if I defined the env variable in another script, the other script is unfortunately unaware of it.

If you are using JupyterLab notebooks, it is best to set environment variable `LIGHTLY_CA_CERTS` when starting the JupyterLab server/container.

**Pull request merged**
