### PR TITLE
Update Docs Makefile to download required datasets

### PR DESCRIPTION
**Pull request by MalteEbner**
## Description
- allows to build the docs without needing to manually download all datasets to the correct location
- Developed mostly by @shaundaley39 

image

### CODE REVIEW

**Comment by japrescott** [comment]
I guess it would be good if we would remove the archives after downloading them? And maybe check if the folder is there before just downloading everything?

**Review by shaundaley39 — CHANGES_REQUESTED** [review]
Agreed with @japrescott 
- it would be better to check whether a dataset directory exists before downloading it (same as with the Clothing dataset, etc)
- it would be better to remove archives after their content is extracted, just to keep things cleaner

**Comment by MalteEbner** [comment]
> * it would be better to remove archives after their content is extracted, just to keep things cleaner

This is done with `make clean` deleting `_data`. I would keep this for now.

**Review by shaundaley39 — APPROVED** [review]

**Comment by shaundaley39** [comment]
Great, I like that this also drops datasets no longer needed for tutorials (and checks for preexistence! And of course, ensures existence of datasets needed for building the docs!).

**Review by IgorSusmelj — APPROVED** [review]
LGTM

**Pull request merged**
