### PR TITLE
Move classes and public functions to top of files

### PR DESCRIPTION
**Pull request by fadkeabhi**
This pull request implements the proposed changes outlined in issue [#1227](https://github.com/lightly-ai/lightly/issues/1227), which involves restructuring the code for improved readability and organization.

### Tasks
- [x] Move public classes and functions to top in lightly/data
- [x] Move public classes and functions to top in lightly/loss
- [x] Move public classes and functions to top in lightly/models/modules
- [x] Move public classes and functions to top in lightly/transforms (No need of cleanup, Already Cleaned)
- [x] Move public classes and functions to top in lightly/utils

### CODE REVIEW

**Review by SauravMaheshkar — APPROVED** [review]
LGTM ☕

**Review by SauravMaheshkar — CHANGES_REQUESTED** [review]
@fadkeabhi could you run `make format`, and commit again. `black` seems to be failing on CI. Remember to use the same version as the one mentioned in `pyproject.toml`

**Comment by fadkeabhi** [comment]
@SauravMaheshkar I have reformatted the files. Was issue with Different version of black on my machine. Issue is resolved now. can you take a look at it again.

**Review by SauravMaheshkar — APPROVED** [review]
LGTM ☕

**Pull request merged**
