### PR TITLE
Philipp add second datasource option docs

### PR DESCRIPTION
**Pull request by philippmwirth**
# Philipp add second datasource option docs

Update documentation to include information about how to configure an "output" datasource.

### CODE REVIEW

**Review by MalteEbner — COMMENTED** [review]
A general question: Do the lights for "list, read, write" apply to the input or output datasource? Shouldn't there be
If only one datasource:
- list, read, write for it
If two datasources:
- list, read for input
- list, read, write for output

**Comment by MalteEbner** [comment]
The last steps (7-9) are the following for the 3 datasources:
> Press save and ensure that at least the lights for List and Read turn green. If you added permissions for writing, this light should also turn green.

> Press save and ensure that all lights turn green.

> After closing the pop-up by clicking the X, you should be on the dataset creation page again.

It would be nice to have this the same for all three datasources

**Review by MalteEbner — CHANGES_REQUESTED** [review]
The text itself is nice, well done!

I am missing an addition to the `make download-noplot` to also get the images under `resources/resources_datasource_configure` downloaded.

**Comment by philippmwirth** [comment]
> 

I have added it to the existing folders so if you do `make clean` and then `make html-noplot` you will get the new images.

**Comment by MalteEbner** [comment]
> I have added it to the existing folders so if you do `make clean` and then `make html-noplot` you will get the new images.

Thanks, I just tried it out and it worked.

**Pull request merged**
