### PR TITLE
restructured documentation

### LINKED ISSUE #463: Clean up navigation
# Clean up navigation

The navbar in the docs has become quite cluttered. Especially the "First Steps" section has a lot of content which does not really belong there. We should regroup and clean it up.

To Do:
- [ ] Regroup / rewrite the introduction sites (see below for a suggestion)

Current state:

grafik

Suggested new structure:

- GETTING STARTED
    - Main Concepts (new page with the content from the current landing page)
    - Installation
    - Command-line Tool
    - Self-supervised Learning (new page with the content from "Lightly at a Glance"
    - Active Learning (move the concepts part to "Main concepts")
    - The Lightly Platform (optional - maybe merge it with AL)
- ADVANCED
    - Advanced Concepts (new page with contents of current "Advanced" page)
    - Benchmarks

**IMPORTANT**
> Just a quick reminder for anyone working on reshuffling our lightly docs page. Make sure your changes don’t affect the URLs as we would have broken links otherwise. I think the urls are from the folder structure but I’m not sure.
~ @IgorSusmelj

### PR DESCRIPTION
**Pull request by MalteEbner**
closes #463

## Description
image

- Created the desired new structure:
```
GETTING STARTED

-     Main Concepts (new page with the content from the current landing page)
-     Installation
-     Command-line Tool
-     Self-supervised Learning (renamed from "Lightly at a Glance")
-     Active Learning (move the concepts part to "Main concepts")
-     The Lightly Platform (optional - maybe merge it with AL)

ADVANCED

-     Advanced Concepts (new page with contents of current "Advanced" page)
-     Benchmarks
```
- No files were renamed, thus the links should be still the same: I checked it and the new "Self-supervised Learning"
(`http://localhost:1234/getting_started/lightly_at_a_glance.html`) and old "Lightly at a Glance" (`https://docs.lightly.ai/getting_started/lightly_at_a_glance.html`) still have the same link

### Follow-Up
The structure does not promote a good user flow for different user groups in my eyes. Thus there is a follow-up issue: https://github.com/lightly-ai/lightly/issues/479

### CODE REVIEW

**Comment by japrescott** [comment]
Generally it looks good but I agree there are some outstanding issues that we need to tackle. I actually thought they are written down (but maybe in a different issue?) regarding to move `The LightlyPlatform` in to a 1stLevel entry next to `On-Prem` and to collapse the `Python API` (Personally I would rename it `Python Reference` to not to confuse it with our API).

Is there some way I can get this running locally?

**Comment by MalteEbner** [comment]
> Is there some way I can get this running locally?

There are instructions in the readme:
https://github.com/lightly-ai/lightly/edit/master/docs/README.md

```bash
cd docs
pip install sphinx
pip install sphinx_rtd_theme
pip install sphinx_gallery

make html
python -m http.server 1234 -d build/html
```

**Comment by japrescott** [comment]
okey.. this will take a while for the docs are built until all the tutorials are built/trained etc :)

**Comment by MalteEbner** [comment]
> okey.. this will take a while for the docs are built until all the tutorials are built/trained etc :)

@japrescoss You don't need to build all tutorials. If you simply don't provide any tokens or correct paths to datasets, then building the tutorials will fail, but the other stuff will work nonetheless. Thus just build it and start the https server, this takes less than a minute.

**Review by IgorSusmelj — APPROVED** [review]

**Pull request merged**
