### PR TITLE
use latest gh actions

### PR DESCRIPTION
**Pull request by japrescott**
upgrade the github workflow actions to use latest versions and thus, supported environments

### CODE REVIEW

**Review by SauravMaheshkar — COMMENTED** [review]
Perhaps we should also look into adding a [dependabot](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide) configuration to the repository?

This would check for the latest available versions as specified and make PRs accordingly. 

An example file could be as follows `.github/dependabot.yml`

```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

**Comment by japrescott** [comment]
Thanks @SauravMaheshkar for the suggestion. I agree that this could be helpful but am afraid to just activate it without careful consideration. Will add this to our backlog for further evaluation 👍

**Review by guarin — APPROVED** [review]
LGTM!

**Review by SauravMaheshkar — APPROVED** [review]
LGTM 🙂

**Pull request merged**
