### PR TITLE
Cleanup: docstrings in the lightly/data subpackage

### PR DESCRIPTION
**Pull request by ChiragAgg5k**
This PR will mark completing cleanup of `_image.py`, `lightly_subset.py` and `multi_view_collage.py` files in the data subpackage according to issue #1689 

after this `_video.py`, `collage.py` and `dataset.py` files will be left, which will be done in separate PRs due to their long size.

### CODE REVIEW

**Comment by ChiragAgg5k** [comment]
seems like tests are failing due to issues not introduced via this pr...

**Comment by ChiragAgg5k** [comment]
ooohh ok got it. fixed it

**Comment by ChiragAgg5k** [comment]
@guarin do review the pr when u can, thanks :D

**Comment by philippmwirth** [comment]
> @guarin do review the pr when u can, thanks :D

Hi @ChiragAgg5k and thanks a lot for your contribution! Before I review, could you please remove the newly typed files from the list of files ignored by mypy [here](https://github.com/lightly-ai/lightly/blob/99a7b137c5dbac380dc157623ec8367f6c8d0262/pyproject.toml#L210)? Thank you!

**Comment by ChiragAgg5k** [comment]
I tried removing files which were formatted from the ignore, and it lead to some errors. i will push the fixes soon

**Comment by ChiragAgg5k** [comment]
@philippmwirth any update?

**Comment by philippmwirth** [comment]
> @philippmwirth any update?

Did you not want to push the fixes first?

**Comment by ChiragAgg5k** [comment]
@philippmwirth yup i do. but i am facing an issue here:

the tests are failing due to an error in the code itself:

Screenshot 2024-11-22 at 1 07 56 PM

**Comment by philippmwirth** [comment]
Thanks, @ChiragAgg5k, I'll take a look.

**Review by philippmwirth — APPROVED** [review]
Thank you @ChiragAgg5k for your help! I quickly fixed the typing problem you encountered.

**Pull request merged**
